name: Sync Fork

on:
  schedule:
    - cron: '0 8 * * *'   # Every day at 8 AM UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main  # Change to 'master' if your default branch is 'master'

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream
        run: git remote add upstream https://github.com/loopandlearn/LoopFollow.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream changes
        run: git merge upstream/main --allow-unrelated-histories --no-edit || true

      - name: Push changes
        run: git push origin main
